FROM ubuntu:20.04
FROM condaforge/miniforge3:latest
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq -y
RUN apt-get install ffmpeg libsm6 libxext6 g++ -y

RUN conda update -n base -c defaults -c conda-forge conda
RUN conda update --all -y

RUN conda install -c conda-forge hyperspy-base -y
RUN conda install astra-toolbox -c astra-toolbox -y
RUN conda install pytest flake8 pydocstyle -y

RUN pip install pystackreg


