FROM continuumio/miniconda3:latest

RUN conda update conda

RUN conda install python=3.7
RUN conda install pytest flake8 pydocstyle -c defaults
RUN conda install hyperspy -c conda-forge
RUN conda install astra-toolbox -c astra-toolbox/label/dev
RUN conda install opencv -c conda-forge

RUN apt-get update -q
RUN apt-get install ffmpeg libsm6 libxext6 g++ -y
RUN pip install pystackreg
