name: Install ETSpy with conda
description: Uses conda package manager to install ETSpy and its dependencies
inputs:
  conda-env-name:
    default: etspy
    type: string
  python-version:
    type: string
    required: true
  macos:
    default: false
    type: boolean
    description: Whether to use MacOS conda environment which does not support CUDA

runs:
  using: "composite"
  steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ${{ inputs.conda-env-name }}
        environment-file: resources/etspy-dev.yml
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        auto-activate-base: false
    - name: Conda list
      run: conda list
      shell: bash -el {0}
    - name: Install etspy development
      # Only install CUDA related packages if not on MacOS
      run: |
        if [ "${{ inputs.macos }}" == "true" ]; then
          pip install --no-deps -e .
        else
          pip install --no-deps -e ".[gpu]"
        fi
      shell: bash -el {0}